"""Reproduce proposal document from directly extracted DOCX paragraphs; never edits source."""
import json
from pathlib import Path

source = json.loads(Path('reconciliation/manuscript_extracted.json').read_text(encoding='utf-8'))
paras = {p['id']: p['text'] for p in source['paragraphs_including_tables']}
items = []
def add(id, locations, replacement, reason, evidence, status='Author decision supports correction; exact manuscript wording awaiting researcher/adviser acceptance'):
    items.append((id, locations, replacement, reason, evidence, status))

add('M01', [3,11], 'Time Series Forecasting of Reportable Infectious Disease Case Counts among Individuals Aged 5–19 in Antipolo City: Implications for Public-School Preparedness (Historical Period: 2016–2025)', 'Distinguishes population and intended benefit from school-acquired cases; resolves title dates. A new title needs author/adviser approval.', 'Handoff §§3.1, 3.2; original titles P0003/P0011; workbook period 2016–2025.', 'Awaiting researcher/adviser decision on title; historical period correction supported by source')
add('M02', [14,16,33], 'This study proposes city-wide monthly forecasting for individuals aged 5–19 in Antipolo City to inform public-school preparedness. The provisional disease categories are Dengue, Leptospirosis, and Measles-Rubella; final coverage and classification await CHO verification and researcher/adviser approval. Existing all-age surveillance records are retained only for separately labeled technical evaluation and do not establish performance for the approved population.', 'School age, source eligibility, and provisional disease coverage must be explicit.', 'Handoff §§3.1–3.4; DATA_RECONCILIATION.md.')
add('M03', [35,37], 'Develop and evaluate a disease-specific hybrid SARIMA–NNAR forecasting pipeline using eligible historical records. Maintain a provisional 12-month forecast capability while the CHO interview determines the operational usefulness of 1-, 3-, or 12-month horizons. Evaluate forecast error against observed holdout case counts and live SARIMA-only and seasonal-naive benchmarks.', 'Retains approved horizon capability without prematurely finalizing operational objectives or promising validated accuracy.', 'Handoff §§3.7–3.8; pipeline evaluation windows.', 'Awaiting researcher/adviser approval of objective wording; horizon remains awaiting CHO confirmation')
add('M04', [26,40,43,79], 'The dashboard is intended to support preparedness discussions by displaying forecast monthly case counts. Resource allocation, intervention selection, outbreak prevention, and reductions in exposure are potential downstream uses to be evaluated by health authorities; the prototype does not perform or demonstrate those outcomes.', 'Operational benefits are intentions, not implemented allocation or measured health outcomes.', 'dashboard/ui/layout.py; dashboard/callbacks/view_callbacks.py; handoff §14.')
add('M05', [41,42], 'The intended beneficiaries include the Antipolo City Health Office and school administrators. Eligible forecasts concern the city-wide population aged 5–19, without asserting public-school enrollment or the location of transmission. All-age technical evaluations are labeled separately.', 'Pediatric terminology is not the approved 5–19 definition; school membership is unavailable.', 'Handoff §§3.1–3.2; source reports lack enrollment fields.')
add('M06', [46], 'The approved analytical population is individuals aged 5–19 in Antipolo City, using confirmed cases once eligible records are supplied and verified. One disease-specific SARIMA–NNAR pipeline will be evaluated for each approved disease category, with the SARIMA forecast plus the NNAR residual forecast as the primary output. Dengue, Leptospirosis, and Measles-Rubella are the provisional categories. Historical all-age data for January 2016–December 2025 are retained for a separate evaluation. Disease count and final classification remain pending verification; no combined cross-disease forecast establishes disease-specific performance.', 'Removes five-model contradiction without prematurely fixing final coverage. NNAR learns residuals, not a separate raw case trajectory.', 'Handoff §§3.1–3.5; baseline pipeline.py::run_hybrid_pipeline.')
add('M07', [47,239,240], 'The recorded local evaluation environment uses Python 3.13.3. Project metadata requires Python 3.12 or later. pandas handles tabular data, statsmodels implements SARIMA and diagnostics, scikit-learn implements the residual neural regressor and scaling, and Plotly Dash provides the interface. Exact installed versions and manifest differences are recorded with each evaluation in TEST_RESULTS.md.', 'Replaces Python 3.11 and records runtime separately from required minimum and unverified pins.', 'python --version directly returned 3.13.3; pyproject.toml:5; requirements.txt; TEST_RESULTS.md.')
add('M08', [49], 'The initial research categories are provisional and will be finalized after CHO consultation and data verification. Other disease labels supported by the general upload software are outside the formal research scope unless separately approved. Their exclusion does not establish that they lack seasonality.', 'Original makes an unsupported blanket seasonal exclusion and conflicts with its own TB seasonal literature discussion P0062.', 'P0049 versus P0062; handoff §3.4.', 'Awaiting adviser approval of delimitation rationale; no scope expansion authorized')
add('M09', [51], 'The intended final analytical dataset contains confirmed cases among individuals aged 5–19. The supplied weekly reports contain all-age aggregates, and their case-classification status is unverified. Those reports support a separately labeled all-age technical evaluation only. Monthly case counts are not population-adjusted incidence rates; mild, unreported, or delayed reports may affect interpretation. City-wide aggregates do not identify individual patients, school enrollment, or transmission settings, and the prototype does not establish legal compliance or causal effects of interventions.', 'Original explicitly admits suspected cases and silently treats them as target data; confidentiality cannot alone establish statutory compliance.', 'Handoff §§3.1–3.3, 6.3–6.4; DATA_RECONCILIATION.md.')
add('M10', [52,85], 'The dashboard is an academic prototype. Software behavior can be tested locally, but production deployment, government-system integration, security assurance, formal CHO acceptance, and expert usability evaluation remain separate activities. Any ISO/IEC-based assessment must specify its selected edition, instrument, respondents, criteria, and actual results before quality ratings are claimed.', 'P0052 excludes security checking while P0085 includes security evaluation. No expert results supplied.', 'P0031/P0052/P0085; tests establish software behavior only.', 'Awaiting researcher/adviser decision on evaluation protocol; CHO acceptance and usability evidence unavailable')
add('M11', [66], 'The cited measles study discusses an imputation method in its own setting. The present implementation does not adopt that method: missing months remain unknown and block forecasting until the source is clarified. Any future imputation method requires a separately justified and approved protocol.', 'Literature method is not automatic authorization to impute local surveillance data.', 'pipeline.py::_validate_observation_coverage; handoff §7.')
add('M12', [80], 'The mandatory hybrid architecture combines a SARIMA case-count forecast with a neural forecast of SARIMA residuals. Its empirical performance is evaluated separately for each eligible disease and population, alongside SARIMA-only and seasonal-naive benchmarks. Hybrid superiority is not assumed, and all unfavorable comparisons are retained.', 'Original asserts neither model could perform as well alone without evidence; historical adverse results already exist.', 'evidence/ historical prediction arrays; THESIS_READINESS.md historical real-data table; MODEL_EVALUATION.md.')
add('M13', [83], 'The supplied development data are weekly, all-age surveillance tables for 2016–2025 transcribed into a workbook. Monthly aggregation uses the month containing the ISO week’s Thursday, with non-ISO week 53 provisionally assigned to December. The CHO must verify its epidemiological-week convention and supply eligible confirmed-case records for ages 5–19. Arithmetic reconciliation is documented independently of epidemiological completeness.', 'Source granularity is weekly, not originally monthly; attribution and approval must remain distinct.', 'dashboard/data/xlsx_parser.py::epi_week_to_month; DATA_RECONCILIATION.md.')
add('M14', [84], 'Preparation validates dates, disease labels, counts, provenance, and observed monthly coverage without inventing missing observations. Seasonal decomposition is a descriptive display, not an input transformation for the forecast pipeline. SARIMA identification uses only each training window, and NNAR models that SARIMA fit’s residuals. Report MAE, RMSE, MAPE with nonzero-actual coverage, and WAPE with zero-denominator handling for the hybrid and its benchmarks. Olana et al. (2025), Table 1, reports a SARIMA test MAPE of 32.22% for national dengue; this external result is historical context, not a universal acceptance threshold or a benchmark computed from Antipolo data.', 'Corrects imputation, unsupported period-specific stationarity, decomposition inputs, omitted WAPE and misuse of 32.22.', 'metrics.py::compute_metrics; publisher Table 1 https://onlinelibrary.wiley.com/doi/10.1155/tbed/7480710; handoff §§10–11.')
add('M15', [97,98], 'The presentation layer displays historical counts, descriptive seasonal decomposition, forecast case counts, diagnostics, error messages, and the empirical forecast error band. The forecasting logic fits each disease’s observed monthly series and passes aligned SARIMA residuals to NNAR; it does not train on a separately decomposed trend or automatically identify causal COVID-related anomalies. Missing-month validation precedes modeling.', 'Code does not train on decomposed components, impute, or implement COVID anomaly classifier.', 'pipeline.py; view_callbacks.py::_build_decomposition_chart; figures.py::fig_decomposition.')
add('M16', [100], 'The prototype uses browser session storage for active tabular data, upload summaries, and serialized forecast results. Pending uploads remain in memory until explicit disease-catalog confirmation. Fitted SARIMA and neural estimator objects are transient during computation; no database or persistent trained-model repository is implemented.', 'Three conceptual databases and saved models are not actual stores.', 'dashboard/ui/layout.py::build_layout; dashboard/modeling/serialization.py; view_callbacks.py::_get_or_compute_disease.')
add('M17', [109,111], 'ADF testing assesses evidence against a unit root in each training series; it does not prove stable variance or all forms of stationarity. Nonseasonal and seasonal differencing are explored within documented finite bounds, with diagnostic limitations retained. Differencing does not continue indefinitely until a desired test result appears.', 'Corrects ADF interpretation and unbounded differencing claim.', 'Revised sarima.py candidate identification; handoff §8; final algorithm details in CHATGPT_RETURN_HANDOFF.md.', 'Technical wording proposed; final algorithm must be checked against verified implementation')
add('M18', [112,113,114], 'For each training window, record ADF and ACF/PACF diagnostics, bounded candidate SARIMA orders, convergence and stability checks, AIC values, and residual diagnostics. Select an admissible candidate using the documented procedure without consulting that window’s future observations. A Ljung–Box result is diagnostic evidence about residual autocorrelation, not proof of white noise or forecast accuracy. Preserve candidate failures and disclose any residual concerns.', 'AIC and residual tests do not prove predictive accuracy. Must match actual selection/rejection procedure.', 'Revised sarima.py; MODEL_EVALUATION.md; handoff §§3.6, 8.', 'Technical wording proposed; implementation and validation status tracked in handoff')
add('M19', [119,122,123,124], 'The residual NNAR implementation is a scikit-learn MLPRegressor using three lagged SARIMA residuals, one hidden layer with four ReLU units, L2 alpha=10.0, L-BFGS optimization, max_iter=2000, and random_state=42. StandardScaler is fitted to training lag features only; targets remain in residual units. Forecasts recurse through predicted residuals. The primary point forecast is max(0, SARIMA forecast + NNAR residual forecast). Convergence warnings and component failures are retained; failed neural fitting must not masquerade as a successful zero correction.', 'Makes implementation reproducible and distinguishes actual architecture from conceptual diagram.', 'config.py NNAR constants; nnar.py::run_nnar; metrics.py::hybrid_forecast; handoff §9.')
add('M20', [163,191,197,207], 'Comparative model properties are context-dependent findings from their cited studies. They do not establish an intrinsic need for a neural model, universal interpretability, or a fixed performance ranking on Antipolo data. Report the experimental setting for each comparison and assess local performance on the same untouched holdout.', 'Tables 1–2 contain universal performance claims; SARIMA need not always require NNAR and RF/LSTM rankings vary.', 'Manuscript Tables 1–2; historical local adverse results.', 'Awaiting adviser review of literature claims and primary-source citation checking')
add('M21', [218], 'ARIMA is a nonseasonal autoregressive integrated moving-average model; SARIMA adds seasonal terms. This study uses the historical period January 2016–December 2025, subject to verified eligible data availability.', 'Glossary unexpectedly uses 2015–2025.', 'P0027/P0033/P0046 versus P0218; source workbook years.')
add('M22', [224,242,246,250], 'Seasonal decomposition is a descriptive visualization separating trend, seasonal, and remainder components. SARIMA residuals used by NNAR are observed counts minus aligned SARIMA fitted values within the training window; they are distinct from the decomposition remainder. Seasonal patterns are assessed from the data rather than assumed for every disease.', 'Avoids conflating two residual definitions and claiming decomposition is model preprocessing.', 'pipeline.py::_run_backtest_leg; view_callbacks.py::_build_decomposition_chart; figures.py::fig_decomposition.')
add('M23', [226,238], 'The prototype displays provisional forecast case counts and data/model error feedback. It does not implement a validated outbreak-detection threshold, automated notification service, or surveillance response workflow.', 'Forecasts and input error messages are not operational outbreak alerts; glossary changes horizon to month-ahead.', 'view_callbacks.py and layout.py; handoff §§3.7, 14.')
add('M24', [234], 'Reportable disease categories are defined by the applicable surveillance source and approved research scope. Dengue, Leptospirosis, and Measles-Rubella are the provisional research categories pending CHO and adviser verification.', 'Glossary says six categories despite three provisional categories; school reporting-law claim requires separate primary legal support.', 'P0046/P0049/P0234; handoff §3.4.')
add('M25', [248], 'The modeled time series consists of city-wide monthly disease case counts, in chronological order. The approved population is ages 5–19 with confirmed cases once eligible data are obtained; current all-age results are separate. School-level observations are not supplied.', 'Glossary claims per-school records whereas source is city-wide.', 'P0051; source PDFs; handoff §§3.1–3.3.')
add('M26', [44], 'This study documents a reproducible SARIMA–NNAR prototype and its benchmarks, data limitations, and evaluation results. Applying it to other diseases or locations requires separate source verification and evaluation.', 'Includes NNAR and avoids treating transferability as demonstrated.', 'Mandatory hybrid decision; historical adverse results.')
add('M27', [257,283,286,290], 'Verify each bibliographic record against the primary publication before submission. Retain one correctly attributed entry per publication/version, distinguish preprints from reviewed articles, and make in-text authors and years match the verified reference record.', 'Plaza and Servillon entries appear to refer to the same preprint; Warnasekara author lists differ between table and bibliography. Other literature claims were not exhaustively source-authenticated in this audit.', 'P0165/P0209/P0290; P0067/P0283/P0286.', 'Awaiting adviser/researcher bibliographic verification; no unverified corrections applied')

intro = '''# Manuscript revision proposals

Date: 2026-09-27. These are reviewable proposals, not edits to the authoritative manuscript. The original DOCX remains untouched. Approval of a research decision authorizes technical correction; it does not mean the researcher has accepted this exact manuscript prose. No proposal is marked resolved merely because it is written here.

The manuscript was read directly from `C:/Users/redlo/Downloads/BRPM_Documentation (2).docx`: 292 XML paragraphs including all three tables, references, and eight embedded diagrams. It contains an introductory chapter and Chapter 2; no separate completed results chapter was present. Paragraph IDs below refer to `reconciliation/manuscript_extracted.txt`, not unstable Word page numbers. Text extraction retains table paragraphs; all eight embedded figures were inspected visually and preserved in `reconciliation/manuscript_media/`. The extraction is not a rendered-layout proofread. External literature was not exhaustively authenticated.

Original SHA-256: `{sha}`.

## Exact text proposals

Where an entry covers multiple paragraphs, the replacement is consolidated prose: place it in the primary section and remove or harmonize duplicated claims rather than copying identical paragraphs repeatedly. Original statements below are full extracted paragraphs, so the review remains independently traceable.
'''.format(sha=source['sha256'])
parts = [intro]
for id, locations, replacement, reason, evidence, status in items:
    parts.append(f'\n### {id}: ' + ', '.join(f'P{n:04}' for n in locations) + '\n')
    for n in locations:
        parts.append(f'**Original P{n:04}:** {paras[n]}\n')
    parts.append(f'**Proposed replacement:** {replacement}\n\n**Reason:** {reason}\n\n**Evidence:** {evidence}\n\n**Approval/application status:** {status}. Original not changed.\n')
Path('MANUSCRIPT_REVISION_PROPOSALS.md').write_text('\n'.join(parts), encoding='utf-8')

supplement = '''
## Embedded diagrams: exact label replacements

These diagram proposals are not applied to the original images. Their research requirements are established; revised drawing layout awaits researcher/adviser acceptance.

| ID / location | Original statement or label | Proposed exact replacement / flow | Reason and evidence | Status |
|---|---|---|---|---|
| M28, Figure 1 IPO, image7.png | “HISTORICAL DISEASE DATASET (2016-2026)” and output title “(2016–2026)” | “Historical observations: 2016–2025; provisional forecast year after complete history: 2026” | Observation and forecast years differ; workbook ends 2025. | Proposed, unapplied |
| M29, Figure 1 | “PYTHON 3.14.7 OR LATEST” | “Recorded runtime: Python 3.13.3; project requirement: Python >=3.12; exact package versions in test report” | Direct interpreter check and pyproject.toml:5; no claim that latest was tested. | Proposed, unapplied |
| M30, Figure 1 | “TARGET MAPE BELOW 32.22%, AS SET BY OLAN ET AL. (2025)” | “Historical external reference: SARIMA test MAPE 32.22%, Olana et al. (2025), Table 1; not an Antipolo acceptance threshold” | Primary publisher Table 1 directly verifies provenance; author's surname is Olana. | Provenance verified; wording proposed |
| M31, Figures 1–2, image7.png/image5.png | “IMPUTE MISSING MONTHLY VALUES”; “flagging COVID-anomalies” | “Validate missing and invalid observations; block incomplete forecast inputs; retain source reporting limitations” | No approved imputation or causal anomaly classification; pipeline coverage validation. | Proposed, unapplied |
| M32, Figures 1–2 | “DISPLAYED CONFIDENCE INTERVALS”; “Displays confidence intervals” | “Display historical maximum-absolute-error band; no validated coverage probability” | pipeline.py::_historical_error_band; no calibrated 95% hybrid coverage established. | Proposed, unapplied |
| M33, Figure 2 Data Tier, image5.png | “Model Storage”; “Stores SARIMA and NNAR data” | “Transient model fitting in process; browser session stores data and serialized result arrays, not fitted model objects” | ui/layout.py::build_layout; modeling/serialization.py. | Proposed, unapplied |
| M34, Figure 4 NNAR, image4.png | Three input nodes and three hidden nodes | Draw 3 residual-lag input nodes, 4 ReLU hidden nodes, and 1 residual output node; caption “Implemented residual MLP architecture (3,4,1)” | config.py NNAR_LAGS=3, NNAR_HIDDEN=(4,); nnar.py. | Proposed, unapplied |
| M35, Figure 5 main flow, image2.png | “Validation passed?” → “Dataset storage” | “Validation passed?” → “Show complete upload disease catalog” → “Explicit user confirmation?” → “Activate uploaded dataset and invalidate cached results” | data_callbacks.py::transition_data_session; existing catalog confirmation workflow. | Proposed, unapplied |
| M36, Figure 7 data storage, image8.png | “Any tracked disease missing from real data?” → “Mock data” → “Store combined dataset” | Remove supplementation branch. “Activate confirmed upload as authoritative dataset; never add synthetic observations. Reset to sample is a separate explicit action.” | combine.py::prepare_uploaded_data; handoff §6.1. Original figure contradicts even preserved baseline. | Proposed, unapplied |
| M37, Figure 8 training, image6.png | “Hybrid scores better than SARIMA on test months?”; “Select SARIMA only as final model”; “Retrain winning model” | “Fit SARIMA candidate and residual NNAR using training observations; if a component fails, try another valid SARIMA candidate, otherwise report explicit hybrid unavailable. Evaluate hybrid and benchmarks on matching periods. Refit mandatory hybrid on available history after evaluation.” | Author mandatory hybrid decision supersedes diagram's conditional model selection. | Proposed, final code status in handoff |
| M38, Figures 3 and 8 | Stationarity/differencing loop; simple train/test branch | Add finite candidate bounds, recorded diagnostics, separate earlier evaluation folds and final untouched holdout; retain failure exit rather than endless differencing. | handoff §§8–10; revised sarima.py/pipeline.py. | Proposed, final algorithm verification required |

## Required methodological additions (no corresponding complete original statement)

**M39 — Evaluation protocol, proposed insertion:** “For a complete January 2016–December 2025 monthly series, use training through December 2022 to evaluate 2023 and training through December 2023 to evaluate 2024. Reserve January–December 2025 as the final holdout after training through December 2024. Perform parameter identification independently within each training window. The holdout does not determine architecture, candidate bounds, or neural settings. After evaluation, refit the approved hybrid using all available history to forecast 2026. Because previous development has already examined the 2025 outcomes, document that historical exposure: an algorithmically excluded holdout is not newly unseen evidence to the research team.” Evidence: historical THESIS_READINESS.md, pipeline evaluation windows, handoff §10. Status: proposed clarification; author/adviser must assess validity of previously observed holdout and decide whether prospective evaluation is additionally required.

**M40 — Metrics, proposed insertion:** “For n matched holdout observations, error e_i=y_i−ŷ_i, MAE=Σ|e_i|/n and RMSE=sqrt(Σe_i²/n). MAPE=100·mean(|e_i|/|y_i|) over nonzero actual observations only; disclose that count and report N/A if none exist. WAPE=100·Σ|e_i|/Σ|y_i|; report N/A when the actual denominator is zero. Report hybrid, SARIMA-only, and seasonal-naive results separately on identical periods; never average synthetic and real populations.” Evidence: metrics.py::compute_metrics. Status: author-required technical correction; proposed manuscript insertion.

**M41 — Source reconciliation, proposed insertion:** “For Dengue 2024, the printed PDF annual total is 4,516 and the sum of weekly observations is 4,588, a difference of 72. The workbook follows weekly observations. Both values and their origins are preserved pending CHO correction; arithmetic consistency does not establish case completeness. Blank cells are distinguished from explicit zero counts, and the weekly calendar remains provisional.” Evidence: DATA_RECONCILIATION.md and preserved original reports. Status: awaiting CHO confirmation; proposed disclosure.

**M42 — Error band, proposed insertion:** “The displayed band adds and subtracts a historical maximum absolute forecasting error from the production point forecast, with the lower limit constrained to nonnegative counts. The calibration window and errors are recorded with the result. No prospective coverage guarantee or validated 95% prediction interval is claimed.” Evidence: pipeline.py::_historical_error_band and result interval_method. Status: proposed; precise calibration-window wording must be checked against final implementation.

**M43 — Historical and revised findings, proposed insertion:** “The prior conditional-selection implementation reported all-age holdout WAPE of 25.17% for Dengue, 67.08% for Leptospirosis, and 162.58% for the category then labeled Measles, against seasonal-naive WAPE of 34.90%, 55.86%, and 50.00%. These are historical results from the earlier implementation, not revised mandatory-hybrid results. The source category is Measles-Rubella. Revised results, failure states, prediction arrays, environment and warnings are reported separately in MODEL_EVALUATION.md.” Evidence: historical THESIS_READINESS.md and evidence artifacts; must not substitute these values for fresh runs. Status: approved transparency requirement; insertion pending manuscript acceptance.

**M44 — Source-population handling, proposed insertion:** “Synthetic demonstration observations, original all-age surveillance, unverified uploads, and verified ages 5–19 confirmed-case records are distinct dataset classes. An upload label or user declaration does not verify eligibility. Analyses must retain source file identity and population/classification metadata. Until the eligible extract is supplied, the approved population evaluation remains unavailable.” Evidence: handoff §§3.1–3.3, 6.1. Status: author-required separation, actual enforcement status in handoff.

## Verified historical-reference provenance

Checked 2026-09-27 against the primary [Olana et al. publisher article, Table 1](https://onlinelibrary.wiley.com/doi/10.1155/tbed/7480710). The table attributes 32.22 to SARIMA testing MAPE. Training covers January 2017–December 2023; testing covers January–December 2024 for nationwide dengue. Thus the number's source is verified, while using it as an acceptance criterion for Antipolo, ages 5–19, other diseases, or a hybrid is not justified by that source. The same paper reports lower testing MAPE for NNAR. Keep the fixed reference separate from the active-dataset benchmark. This is a provenance finding, not reproduction of the paper's experiment.

## Coverage and limits

Reviewed title/front matter; introduction/background; objectives; significance; scope/delimitations; Chapter 2 literature/design concept; all architecture explanations; Figures 1–8; comparative Tables 1–2; definitions Table 3; and all bibliography entries. Additional chronology, citation attribution, and causal claims remain candidates for adviser-led primary literature checking. The displayed November 10, 2026 cover date is later than this audit and should be confirmed as the intended submission date rather than silently changed. No CHO interview, expert usability assessment, clinical evaluation, ethics approval, or school-specific transmission study was supplied or inferred.
'''
with Path('MANUSCRIPT_REVISION_PROPOSALS.md').open('a', encoding='utf-8') as handle:
    handle.write(supplement)
